/* Statistical Inference 互動式考題 — 題庫資料（中英雙語版）
 * Bilingual question bank for Statistical Inference Tutorial.
 * 題型 type: "single" 單選 | "multi" 多選 | "tf" 是非
 * 單選 ans: "A"|"B"|"C"|"D"   多選 ans: ["A","C"]   是非 ans: "T"|"F"
 */
window.QUIZ_DATA = {
  statinf: {
    label: "Statistical Inference 互動考題",
    label_en: "Statistical Inference Interactive Quiz",
    labels_en: {
      "頻率學派基礎": "Frequentist Foundations",
      "迴歸與 GLM": "Regression & GLM",
      "貝氏推論": "Bayesian Inference",
      "生物資訊應用": "Bioinformatics Applications",
      "Step 1：機率與分布": "Step 1: Probability & Distributions",
      "Step 2：點估計與抽樣分布": "Step 2: Point Estimation & Sampling",
      "Step 3：信賴區間與 Bootstrap": "Step 3: Confidence Intervals & Bootstrap",
      "Step 4：假設檢定與錯誤": "Step 4: Hypothesis Testing & Errors",
      "Step 5：常見檢定方法": "Step 5: Common Tests",
      "Step 6：線性迴歸與診斷": "Step 6: Linear Regression & Diagnostics",
      "Step 7：ANOVA / 混合模型": "Step 7: ANOVA / Mixed Models",
      "Step 8：Logistic 迴歸與 OR": "Step 8: Logistic Regression & OR",
      "Step 9：GLM 計數模型": "Step 9: GLM Count Models",
      "Step 10：貝氏定理、先驗、後驗": "Step 10: Bayes / Priors / Posteriors",
      "Step 11：MCMC、HMC 與診斷": "Step 11: MCMC, HMC & Diagnostics",
      "Step 12：後驗摘要、BF、PPC": "Step 12: Posterior Summaries, BF, PPC",
      "Step 13：階層 / 經驗貝氏": "Step 13: Hierarchical / Empirical Bayes",
      "Step 14：多重檢定與 FDR": "Step 14: Multiple Testing & FDR",
      "Step 15：差異表現統計": "Step 15: DE Statistics",
      "Step 16：排列、Bootstrap、GSEA": "Step 16: Permutation / Bootstrap / GSEA",
      "Step 17：存活分析": "Step 17: Survival Analysis"
    },
    subjects: {
      "頻率學派基礎": {
        "Step 1：機率與分布": [
          { type:"single",
            stem:"RNA-seq 計數通常違反 Poisson 假設的主要原因是？",
            stem_en:"Why do RNA-seq counts typically violate Poisson assumptions?",
            A:"計數不是整數", A_en:"Counts are not integers",
            B:"樣本數太多", B_en:"Too many samples",
            C:"生物變異使 Var > Mean（過度離散）", C_en:"Biological variation makes Var > Mean (overdispersion)",
            D:"Poisson 的期望值無限大", D_en:"Poisson has infinite expectation",
            ans:"C",
            exp:"生物與技術變異使 Var/Mean > 1，這是 overdispersion，也是 NB 取代 Poisson 的根本原因。",
            exp_en:"Biological + technical variation pushes Var/Mean > 1 — overdispersion — which is exactly why NB replaces Poisson." },
          { type:"single",
            stem:"關於中央極限定理 (CLT) 的敘述何者正確？",
            stem_en:"Which statement about the CLT is correct?",
            A:"CLT 要求 X 本身必須常態", A_en:"CLT requires X itself to be normal",
            B:"在 iid 與有限變異數下，樣本均值的抽樣分布漸近常態", B_en:"Under iid & finite variance, the sample mean's sampling distribution becomes asymptotically normal",
            C:"CLT 對相關樣本仍然成立", C_en:"CLT holds even for correlated samples",
            D:"CLT 對 Cauchy 分布也成立", D_en:"CLT holds for the Cauchy distribution",
            ans:"B",
            exp:"CLT 對任何有限變異數的 iid 樣本均值都有效，不需 X 本身常態；Cauchy 變異數無限不適用。",
            exp_en:"CLT applies to any iid mean with finite variance; X itself need not be normal. Cauchy has infinite variance and is excluded." },
          { type:"tf",
            stem:"是非題：log(count+1) 後跑 t-test 等同於假設轉換後常態，對 low-count 基因近似很差。",
            stem_en:"True/False: Running a t-test on log(count+1) assumes post-transformation normality, which is poor for low-count genes.",
            ans:"T",
            exp:"這正是 DESeq2/edgeR 採用 NB GLM 而非 log+t-test 的根本理由。",
            exp_en:"Exactly why DESeq2/edgeR use NB GLM instead of log+t-test." }
        ],
        "Step 2：點估計與抽樣分布": [
          { type:"single",
            stem:"為什麼 MLE 估計母體變異數 σ² 時會「向下偏誤」？",
            stem_en:"Why is the MLE of population variance σ² biased downward?",
            A:"因為 MLE 不一致", A_en:"Because MLE is inconsistent",
            B:"因為 MLE 用 1/n 而非 1/(n−1) 作分母，未校正自由度", B_en:"Because MLE uses 1/n instead of 1/(n−1), failing to correct for degrees of freedom",
            C:"因為樣本變異數無限大", C_en:"Because sample variance is infinite",
            D:"因為 Var 永遠等於 Mean", D_en:"Because Var always equals Mean",
            ans:"B",
            exp:"MLE 用 1/n 而非 1/(n−1)，使估計值平均較真值小；無偏估計需要 Bessel 校正。",
            exp_en:"MLE divides by n rather than (n−1); unbiased estimation requires Bessel's correction." },
          { type:"single",
            stem:"Cramér-Rao 下界 (CRLB) 主要規範了什麼？",
            stem_en:"What does the Cramér-Rao lower bound (CRLB) bound?",
            A:"估計量的偏誤上限", A_en:"The maximum bias of an estimator",
            B:"任意無偏估計量變異數的下限（由 Fisher information 決定）", B_en:"The minimum variance of any unbiased estimator (set by Fisher information)",
            C:"MLE 收斂速率", C_en:"The convergence rate of MLE",
            D:"樣本數需求", D_en:"The sample-size requirement",
            ans:"B",
            exp:"CRLB = 1/I(θ)，任何無偏估計量變異數都不可能低於這個界。",
            exp_en:"CRLB = 1/I(θ); no unbiased estimator can have variance below this bound." },
          { type:"tf",
            stem:"是非題：limma / DESeq2 採用「偏誤但縮收」的估計，是因為在 MSE 意義下可優於無偏 MLE。",
            stem_en:"True/False: limma / DESeq2 use biased shrinkage estimators because they can beat unbiased MLE in MSE.",
            ans:"T",
            exp:"James-Stein 已證明在 k≥3 維問題下，向共同平均收縮的估計量 MSE 永遠優於原始 MLE。",
            exp_en:"James-Stein showed that for k≥3 dimensions, shrinking toward a common mean strictly dominates MLE in MSE." }
        ],
        "Step 3：信賴區間與 Bootstrap": [
          { type:"single",
            stem:"95% 信賴區間的「頻率學派正確解讀」是？",
            stem_en:"The correct frequentist interpretation of a 95% CI is?",
            A:"真實參數有 95% 機率落在此區間", A_en:"True parameter has a 95% probability of lying in this interval",
            B:"95% 重複試驗中，以此方法構造的區間將涵蓋真實參數", B_en:"In 95% of repeated trials, intervals constructed this way will cover the true parameter",
            C:"95% 的資料落在此區間", C_en:"95% of the data fall within this interval",
            D:"95% 的後驗質量在此區間", D_en:"95% of posterior mass is in this interval",
            ans:"B",
            exp:"頻率學派 CI 是「程序性」涵蓋——A 是貝氏 credible interval 的解讀；D 是後驗 HDI/ETI。",
            exp_en:"Frequentist CI is a procedural coverage statement. (A) describes a Bayesian credible interval; (D) describes the posterior HDI/ETI." },
          { type:"single",
            stem:"當對統計量做 bootstrap 時，下列何者 BCa 校正會明顯優於 percentile 法？",
            stem_en:"When does BCa bootstrap meaningfully outperform the percentile method?",
            A:"資料極度對稱、樣本極大", A_en:"Highly symmetric data with very large samples",
            B:"統計量的抽樣分布偏態或有偏差時", B_en:"When the statistic's sampling distribution is skewed or biased",
            C:"完全沒有變異時", C_en:"When there is no variation at all",
            D:"分布為高維時", D_en:"In high dimensions",
            ans:"B",
            exp:"BCa 同時校正 bias 與 acceleration（偏態），適用於 sampling 分布偏態的統計量。",
            exp_en:"BCa corrects both bias and acceleration (skewness) — designed for skewed sampling distributions." },
          { type:"tf",
            stem:"是非題：對 sample maximum 等極端統計量，傳統 nonparametric bootstrap 效果良好。",
            stem_en:"True/False: The traditional nonparametric bootstrap works well for extreme statistics like the sample maximum.",
            ans:"F",
            exp:"Bootstrap 對極端值統計收斂失敗——抽出的最大值幾乎永遠就是原樣本最大值，需要 m-out-of-n 或 subsampling。",
            exp_en:"The bootstrap fails for extremes — the resampled max almost always equals the original max; m-out-of-n or subsampling is needed." }
        ],
        "Step 4：假設檢定與錯誤": [
          { type:"single",
            stem:"關於 p-value，下列敘述何者正確？",
            stem_en:"Which statement about p-values is correct?",
            A:"p-value 是 H0 為真的機率", A_en:"p-value is the probability that H0 is true",
            B:"在 H0 為真的前提下，觀察到當前或更極端資料的機率", B_en:"Probability of observing data at least as extreme as current, assuming H0 is true",
            C:"小 p-value 證明替代假設 H1 為真", C_en:"A small p-value proves H1 is true",
            D:"p-value 與樣本數無關", D_en:"p-value is independent of sample size",
            ans:"B",
            exp:"p-value 是條件機率 P(資料極端 | H0)，不是 P(H0) 或 P(H1)；大樣本下任何細微效應 p 值都會變小。",
            exp_en:"p-value is the conditional P(extreme data | H0), not P(H0) or P(H1); with large n any tiny effect produces small p." },
          { type:"single",
            stem:"檢定力 (power = 1 − β) 主要受哪三個因素共同決定？",
            stem_en:"Statistical power (1 − β) is jointly determined by which three factors?",
            A:"樣本數、效應量、顯著水準 α", A_en:"Sample size, effect size, significance level α",
            B:"研究類型、SD、p-value", B_en:"Study type, SD, p-value",
            C:"H0、H1、樣本平均", C_en:"H0, H1, sample mean",
            D:"FDR、FWER、MAD", D_en:"FDR, FWER, MAD",
            ans:"A",
            exp:"標準 power 計算公式直接由 n、effect size、α 與分布變異決定。",
            exp_en:"Standard power calculations are functions of n, effect size, α, and the underlying variance." },
          { type:"tf",
            stem:"是非題：「p > 0.05」就等於「沒有效果存在」。",
            stem_en:"True/False: p > 0.05 means 'no effect exists'.",
            ans:"F",
            exp:"Absence of evidence is not evidence of absence；要主張「等效」應使用 TOST 等價檢定。",
            exp_en:"Absence of evidence is not evidence of absence; to claim equivalence use TOST." }
        ],
        "Step 5：常見檢定方法": [
          { type:"single",
            stem:"在比較兩組獨立樣本均值時，下列何時應優先選擇 Welch's t 而非 Student's t？",
            stem_en:"When should you prefer Welch's t over Student's t for two-sample comparison?",
            A:"當樣本數相同時", A_en:"When sample sizes are equal",
            B:"當兩組變異數可能不相等時（即為預設安全選擇）", B_en:"When two-group variances may differ — the safer default",
            C:"當資料完全常態時", C_en:"When data are perfectly normal",
            D:"當樣本量極小時 (<3)", D_en:"With tiny samples (<3)",
            ans:"B",
            exp:"R 預設 t.test 即為 Welch；不假設等變異，幾乎沒有犧牲就避免了等變異違反帶來的型 I 錯誤膨脹。",
            exp_en:"R's t.test defaults to Welch — does not assume equal variance, virtually no power loss, avoids Type I inflation from variance heterogeneity." },
          { type:"single",
            stem:"Mann-Whitney U / Wilcoxon rank-sum 檢定的虛無假設是？",
            stem_en:"The null hypothesis of the Mann-Whitney U / Wilcoxon rank-sum test is?",
            A:"兩組均值相等", A_en:"Two group means are equal",
            B:"兩組中位數相等", B_en:"Two group medians are equal",
            C:"兩組分布隨機支配關係相等（P(X<Y) = 0.5）", C_en:"Equal stochastic dominance (P(X<Y) = 0.5)",
            D:"兩組變異數相等", D_en:"Two group variances are equal",
            ans:"C",
            exp:"它檢定的是 stochastic dominance，僅在分布形狀相同時才嚴格等同檢定中位數差。",
            exp_en:"It tests stochastic dominance, equivalent to a median test only when the two distributions share the same shape." },
          { type:"tf",
            stem:"是非題：與其對所有兩兩組做多次 t-test，更適合先用 ANOVA 或 Kruskal-Wallis 做全局檢定再做事後比較。",
            stem_en:"True/False: Rather than multiple pairwise t-tests across groups, an omnibus ANOVA/Kruskal followed by post-hoc is preferable.",
            ans:"T",
            exp:"全局檢定控制總體型 I 錯誤；事後 Tukey HSD/Dunn 已校正多重比較。",
            exp_en:"Omnibus controls overall Type I; post-hoc Tukey HSD / Dunn adjusts for multiplicity." }
        ]
      },
      "迴歸與 GLM": {
        "Step 6：線性迴歸與診斷": [
          { type:"single",
            stem:"OLS 迴歸的哪一個假設被異質變異 (heteroscedasticity) 違反，常見補救方法為何？",
            stem_en:"Which OLS assumption is violated by heteroscedasticity, and what is the standard remedy?",
            A:"線性假設；改用 GAM", A_en:"Linearity; use GAM",
            B:"等變異 (homoscedasticity)；改用 HC3 sandwich 穩健 SE 或加權最小平方", B_en:"Homoscedasticity; use HC3 sandwich SE or weighted LS",
            C:"獨立性；改用混合模型", C_en:"Independence; use mixed models",
            D:"無多重共線性；改用 PCA", D_en:"No multicollinearity; use PCA",
            ans:"B",
            exp:"異質變異不會偏誤係數，但讓 OLS SE 失效——HC3 / sandwich 是直接的修正方式。",
            exp_en:"Heteroscedasticity does not bias coefficients but invalidates OLS SE — HC3/sandwich is the direct fix." },
          { type:"single",
            stem:"VIF (Variance Inflation Factor) 高代表什麼？",
            stem_en:"What does a high VIF indicate?",
            A:"係數估計嚴重偏誤", A_en:"Severely biased coefficient estimates",
            B:"多重共線性使 SE 膨脹，但係數仍無偏", B_en:"Multicollinearity inflates SE, but coefficients remain unbiased",
            C:"資料不夠多", C_en:"Insufficient data",
            D:"模型違反線性", D_en:"Linearity is violated",
            ans:"B",
            exp:"共線性不影響 β̂ 期望值（仍 BLUE），但使 Var(β̂) 膨脹，難以判斷個別係數顯著性。",
            exp_en:"Collinearity does not bias β̂ (still BLUE) but inflates Var(β̂), making individual significance hard to detect." },
          { type:"tf",
            stem:"是非題：Cook's distance 結合「槓桿值 (leverage)」與「殘差大小」，用以識別有影響力的觀察點。",
            stem_en:"True/False: Cook's distance combines leverage and residual magnitude to identify influential observations.",
            ans:"T",
            exp:"D_i ≈ (e_i² / (p·s²)) · (h_ii / (1−h_ii)²)，同時反映預測偏差與位置偏離。",
            exp_en:"D_i ≈ (e_i² / (p·s²)) · (h_ii / (1−h_ii)²) — captures both predictive deviation and positional leverage." }
        ],
        "Step 7：ANOVA / 混合模型": [
          { type:"single",
            stem:"何時應把 batch 效應建模為「隨機效應」而非「固定效應」？",
            stem_en:"When should a batch effect be modeled as random rather than fixed?",
            A:"當 batch 水準明確且窮舉、不希望推廣到更大母體時", A_en:"When batch levels are exhaustive and not generalizable",
            B:"當 batch 水準視為來自更大母體的可交換樣本，且希望推廣時", B_en:"When batch levels are exchangeable samples from a larger population and you wish to generalize",
            C:"batch 永遠用 fixed effects", C_en:"Batch should always be fixed",
            D:"沒差別", D_en:"It does not matter",
            ans:"B",
            exp:"Random effects 把 batch 視為母體中可交換樣本，能對「未來新 batch」推論，並節省自由度。",
            exp_en:"Random effects treat batches as exchangeable samples from a population, enabling inference about unseen batches and saving df." },
          { type:"single",
            stem:"什麼是「部分匯整 (partial pooling)」，它解決了什麼問題？",
            stem_en:"What is 'partial pooling' and what problem does it solve?",
            A:"完全合併各群——丟失差異", A_en:"Complete pooling — loses group differences",
            B:"不合併各群——小樣本群極不穩定", B_en:"No pooling — small groups unstable",
            C:"以階層先驗向群間共同平均收縮，平衡完全匯整與不匯整的偏差—變異權衡", C_en:"Shrinks group means toward a common mean via hierarchical prior, balancing bias–variance",
            D:"用 PCA 把群數降維", D_en:"Reduces group dimension by PCA",
            ans:"C",
            exp:"Partial pooling 對小樣本群給較強收縮，對大樣本群幾乎不收縮——MSE 最佳化。",
            exp_en:"Partial pooling shrinks small groups more, large groups less — MSE-optimal across groups." },
          { type:"tf",
            stem:"是非題：混合模型 (lmer) 的 p-value 有爭議，常見解法包含 Satterthwaite df、Kenward-Roger 校正或 parametric bootstrap。",
            stem_en:"True/False: Mixed-model p-values are controversial; standard fixes include Satterthwaite df, Kenward-Roger, or parametric bootstrap.",
            ans:"T",
            exp:"由於 random effect 之 df 不存在解析解，lme4 預設不報 p；lmerTest / pbkrtest 提供近似。",
            exp_en:"Random-effect df has no analytic form; lme4 reports no p by default — lmerTest / pbkrtest provide approximations." }
        ],
        "Step 8：Logistic 迴歸與 OR": [
          { type:"single",
            stem:"什麼情況下 odds ratio (OR) 是 relative risk (RR) 的不良近似？",
            stem_en:"When is the odds ratio a poor approximation to the relative risk?",
            A:"罕見事件 (incidence < 1%)", A_en:"Rare events (incidence < 1%)",
            B:"常見事件 (incidence > 10%) — OR 會明顯誇大 RR", B_en:"Common events (incidence > 10%) — OR overstates RR",
            C:"任何情況都相等", C_en:"They are always equal",
            D:"連續結果", D_en:"Continuous outcomes",
            ans:"B",
            exp:"OR ≈ RR 僅在事件率很低時成立；常見結果應改用 log-binomial 或 Poisson + robust SE 直接估計 RR。",
            exp_en:"OR ≈ RR only for rare events; for common outcomes use log-binomial or Poisson + robust SE to estimate RR directly." },
          { type:"single",
            stem:"Logistic 迴歸出現「完全分離 (separation)」時，MLE 行為與標準解法為何？",
            stem_en:"What happens with 'separation' in logistic regression, and what is the standard fix?",
            A:"MLE 不存在/發散；以 Firth 偏誤校正 (logistf/brglm2) 補救", A_en:"MLE diverges/does not exist; use Firth bias-reduced MLE (logistf/brglm2)",
            B:"MLE 收斂良好，無需處理", B_en:"MLE converges fine, no action needed",
            C:"用 PCA 降維解決", C_en:"Solve via PCA",
            D:"改用 GAM", D_en:"Switch to GAM",
            ans:"A",
            exp:"完美分離下 logit 線性預測 → ±∞，β̂ 無有限解；Firth penalization 加 Jeffreys 先驗修正。",
            exp_en:"Under perfect separation, logit linear predictor → ±∞ so β̂ has no finite MLE; Firth's penalization adds a Jeffreys prior." },
          { type:"tf",
            stem:"是非題：一個模型可以有高 AUC 但校準不良——AUC 高代表排序好，不代表預測機率本身可信。",
            stem_en:"True/False: A model can have high AUC yet poor calibration — AUC measures ranking, not how trustworthy predicted probabilities are.",
            ans:"T",
            exp:"AUC 為 rank-based；要評估機率合理性需 calibration plot / Brier score / Hosmer-Lemeshow。",
            exp_en:"AUC is rank-based; calibration requires calibration plots / Brier score / Hosmer-Lemeshow." }
        ],
        "Step 9：GLM 計數模型": [
          { type:"single",
            stem:"為何 Poisson 模型套在 RNA-seq counts 上常產生大量假陽性？",
            stem_en:"Why does fitting Poisson to RNA-seq counts often produce many false positives?",
            A:"Poisson 計算太慢", A_en:"Poisson is too slow",
            B:"Poisson 假設 Var = Mean，過度離散使 SE 被低估，p-value 偏小", B_en:"Poisson assumes Var = Mean; overdispersion underestimates SE and inflates significance",
            C:"Poisson 不支援整數", C_en:"Poisson cannot handle integers",
            D:"Poisson 無自由度", D_en:"Poisson has no df",
            ans:"B",
            exp:"當真實 Var > Mean 時，Poisson 的標準誤太小，Wald/LR 統計量過大——這正是 DESeq2/edgeR 必用 NB GLM 的原因。",
            exp_en:"When true Var > Mean, Poisson SE is too small and Wald/LR stats are inflated — exactly why DESeq2/edgeR use NB GLM." },
          { type:"single",
            stem:"在計數模型中加入 offset = log(library_size) 的目的是？",
            stem_en:"What does an offset of log(library_size) accomplish in a count GLM?",
            A:"加快計算", A_en:"Speed up computation",
            B:"使模型直接對「率」(rate per library) 建模，係數仍為 log-rate 變化", B_en:"Model rate (per library), so coefficients remain log-rate changes",
            C:"使係數變成截距", C_en:"Turn coefficients into intercepts",
            D:"消除過度離散", D_en:"Eliminate overdispersion",
            ans:"B",
            exp:"Offset 對應到 log(μ) = Xβ + log(size)，即 μ/size = exp(Xβ)，建模速率 (count per unit exposure)。",
            exp_en:"Offset corresponds to log(μ) = Xβ + log(size), i.e. μ/size = exp(Xβ) — modelling rate per unit exposure." },
          { type:"tf",
            stem:"是非題：用 Pearson χ²/df（接近 1 表合適）作 Poisson 過度離散診斷。",
            stem_en:"True/False: Use Pearson χ²/df (≈ 1 means good) to diagnose Poisson overdispersion.",
            ans:"T",
            exp:"χ²/df 顯著 > 1 表示 Var > Mean，應改用 NB / quasi-Poisson / ZINB。",
            exp_en:"χ²/df notably > 1 indicates Var > Mean — switch to NB / quasi-Poisson / ZINB." }
        ]
      },
      "貝氏推論": {
        "Step 10：貝氏定理、先驗、後驗": [
          { type:"single",
            stem:"關於「flat prior 是非資訊先驗」這個說法，何者正確？",
            stem_en:"About the claim 'flat priors are non-informative', which is correct?",
            A:"完全正確", A_en:"Completely correct",
            B:"錯誤——在參數重新轉換後，原本均勻的先驗會變得有資訊性", B_en:"Wrong — under reparameterization, a uniform prior becomes informative",
            C:"取決於樣本量", C_en:"Depends on sample size",
            D:"取決於後驗", D_en:"Depends on the posterior",
            ans:"B",
            exp:"例如 σ² 上均勻 ≠ log σ 上均勻；非資訊性需要 Jeffreys 先驗或仔細選擇尺度。",
            exp_en:"Uniform on σ² is not the same as uniform on log σ; 'non-informative' usually requires Jeffreys priors or careful scale choice." },
          { type:"single",
            stem:"Poisson 速率 λ 的共軛先驗為何？對應後驗分布為？",
            stem_en:"What is the conjugate prior for the Poisson rate λ, and what is the resulting posterior?",
            A:"Beta；後驗仍為 Beta", A_en:"Beta; posterior Beta",
            B:"Normal；後驗為 t", B_en:"Normal; posterior t",
            C:"Gamma(α, β)；後驗為 Gamma(α + Σx, β + n)", C_en:"Gamma(α, β); posterior Gamma(α + Σx, β + n)",
            D:"Uniform；後驗為 Uniform", D_en:"Uniform; posterior Uniform",
            ans:"C",
            exp:"Gamma 是 Poisson 速率的共軛先驗，更新規則簡潔且閉式可解。",
            exp_en:"Gamma is conjugate to the Poisson rate; the update is closed-form." },
          { type:"tf",
            stem:"是非題：在樣本數很大時，先驗選擇通常對後驗影響不大；在小樣本時，先驗選擇至關重要。",
            stem_en:"True/False: With large n, prior choice usually matters little; with small n, prior choice is critical.",
            ans:"T",
            exp:"資料量 → ∞ 時，似然主宰後驗；小樣本時應做 prior-sensitivity check。",
            exp_en:"As n → ∞, likelihood dominates the posterior; for small samples run prior-sensitivity checks." }
        ],
        "Step 11：MCMC、HMC 與診斷": [
          { type:"single",
            stem:"R-hat (Gelman-Rubin) 用於診斷什麼？可接受的閾值是？",
            stem_en:"What does R-hat (Gelman-Rubin) diagnose, and what is the acceptable threshold?",
            A:"模型 fit goodness；R-hat > 5 為佳", A_en:"Model fit; R-hat > 5 is good",
            B:"MCMC 鏈間收斂；通常要求 < 1.01（嚴格時 1.005）", B_en:"Inter-chain MCMC convergence; usually < 1.01 (strictly 1.005)",
            C:"樣本獨立性；> 100 為佳", C_en:"Sample independence; > 100 is good",
            D:"Type I 錯誤率", D_en:"Type I error",
            ans:"B",
            exp:"R-hat 比較鏈間/鏈內變異，> 1.01 即建議延長 warm-up 或重參數化。",
            exp_en:"R-hat compares between/within chain variance; > 1.01 means extend warm-up or reparameterize." },
          { type:"single",
            stem:"HMC 出現 divergent transitions 的處理方式為何？",
            stem_en:"How should you handle divergent transitions in HMC?",
            A:"忽略，因為不影響結果", A_en:"Ignore them — no impact",
            B:"提高 adapt_delta 或對階層模型採用 non-centered 參數化", B_en:"Raise adapt_delta or use non-centered parameterization for hierarchical models",
            C:"刪除整個資料集", C_en:"Discard the dataset",
            D:"改用 Metropolis-Hastings", D_en:"Switch to Metropolis-Hastings",
            ans:"B",
            exp:"Divergences 暗示後驗幾何病態（funnel），non-centered 參數化或更精細的 step size 是標準對策。",
            exp_en:"Divergences signal a pathological posterior geometry (funnel); non-centered parameterization or smaller step size are standard fixes." },
          { type:"tf",
            stem:"是非題：對複雜階層模型 NUTS（HMC 的自適應變體）通常比 Gibbs 取樣效率更高。",
            stem_en:"True/False: For complex hierarchical models, NUTS (adaptive HMC) is typically more efficient than Gibbs sampling.",
            ans:"T",
            exp:"HMC 利用梯度有效探索高維與強相關的後驗；Gibbs 在相關性強時混合極慢。",
            exp_en:"HMC uses gradients to traverse correlated, high-dim posteriors efficiently; Gibbs mixes very slowly under strong correlations." }
        ],
        "Step 12：後驗摘要、BF、PPC": [
          { type:"single",
            stem:"關於 95% credible interval 的正確解讀為？",
            stem_en:"The correct interpretation of a 95% credible interval is?",
            A:"重複試驗中 95% 的區間涵蓋真值", A_en:"95% of repeated intervals cover the truth",
            B:"在當前資料與模型下，θ 有 95% 機率落於此區間", B_en:"Given data + model, θ has 95% probability of lying in this interval",
            C:"95% 的資料落在此區間", C_en:"95% of data fall in this interval",
            D:"95% 的樣本平均落於此", D_en:"95% of sample means fall here",
            ans:"B",
            exp:"這正是「人們通常以為 CI 的意思」——只有 credible interval 才真正擁有這個機率語義。",
            exp_en:"This is the interpretation people often mistakenly attribute to CIs — only credible intervals truly carry this probability semantics." },
          { type:"single",
            stem:"為何 Bayes factor (BF) 對先驗的尺度非常敏感？",
            stem_en:"Why is the Bayes factor (BF) very sensitive to prior scale?",
            A:"BF 不依賴先驗", A_en:"BF does not depend on the prior",
            B:"BF = 邊際似然比 = ∫ p(y|θ)p(θ)dθ 的比，先驗散佈大會自動懲罰複雜模型 (Lindley's paradox)", B_en:"BF = ratio of marginal likelihoods ∫ p(y|θ)p(θ)dθ; vague priors automatically penalize complex models (Lindley's paradox)",
            C:"BF 與 p-value 等價", C_en:"BF equals the p-value",
            D:"BF 永遠 = 1", D_en:"BF is always 1",
            ans:"B",
            exp:"BF 涉及對先驗的積分，先驗越散，「平均」似然越小，因而本質上是先驗-依賴的。",
            exp_en:"BF integrates over the prior; broader priors give smaller average likelihoods — BF is intrinsically prior-dependent." },
          { type:"tf",
            stem:"是非題：Posterior predictive check (PPC) 能揭露「模型在描述觀測資料分布上的失準」，而 R-hat 無法。",
            stem_en:"True/False: Posterior predictive checks (PPC) reveal model misfit to observed data distributions; R-hat does not.",
            ans:"T",
            exp:"R-hat 只診斷取樣收斂，不評估模型本身合適度；PPC 比較 y vs y_rep 是模型批判的關鍵。",
            exp_en:"R-hat only checks sampler convergence, not model adequacy; PPC compares y vs y_rep — the key for model criticism." }
        ],
        "Step 13：階層 / 經驗貝氏": [
          { type:"single",
            stem:"為何縮收 (shrinkage) 在 MSE 意義下能優於每基因獨立的 MLE？",
            stem_en:"Why does shrinkage improve MSE over per-gene MLE?",
            A:"它讓估計量無偏", A_en:"It makes estimators unbiased",
            B:"以可接受的偏誤換取更大的變異數降幅 (James-Stein)", B_en:"It trades acceptable bias for a larger reduction in variance (James-Stein)",
            C:"它縮小樣本", C_en:"It shrinks the sample",
            D:"它增加自由度", D_en:"It increases df",
            ans:"B",
            exp:"James-Stein 已證明 k≥3 維下，向共同平均收縮的估計 MSE 永遠勝過無偏 MLE。",
            exp_en:"James-Stein proved that in k≥3 dimensions, shrinkage toward a common mean dominates unbiased MLE in MSE." },
          { type:"single",
            stem:"limma 的 eBayes() 實際上對什麼做縮收？這帶來什麼好處？",
            stem_en:"What does limma's eBayes() actually shrink, and what does that buy you?",
            A:"係數本身；使係數變大", A_en:"The coefficients; makes them larger",
            B:"基因變異數 s_g² 向共同先驗收縮，產生穩定的 moderated t-statistic", B_en:"Gene-wise variances s_g² are shrunk toward a common prior, yielding stable moderated t-statistics",
            C:"樣本平均；使資料常態化", C_en:"Sample means; normalizes the data",
            D:"FDR 直接縮收", D_en:"Directly shrinks the FDR",
            ans:"B",
            exp:"在每基因 n 極小 (常 3-5) 時，s_g² 極不穩——加入跨基因先驗能讓 t-stat 自由度有效提升。",
            exp_en:"With tiny per-gene n (often 3-5), s_g² is unstable; a cross-gene prior raises the effective df of the t-stat." },
          { type:"tf",
            stem:"是非題：經驗貝氏 (EB) 因忽略「超先驗 (hyperprior) 的不確定性」，其 CI 通常偏窄。",
            stem_en:"True/False: Empirical Bayes (EB) tends to produce CIs that are too narrow because it ignores hyperprior uncertainty.",
            ans:"T",
            exp:"要正確傳播超參數不確定性，需要完整階層貝氏 (full hierarchical Bayes)。",
            exp_en:"Full hierarchical Bayes properly propagates hyperparameter uncertainty." }
        ]
      },
      "生物資訊應用": {
        "Step 14：多重檢定與 FDR": [
          { type:"single",
            stem:"為什麼在基因體尺度檢測中，FDR (false discovery rate) 通常比 FWER (family-wise error rate) 更實用？",
            stem_en:"Why is FDR usually more practical than FWER for genome-wide screens?",
            A:"FDR 較容易計算", A_en:"FDR is easier to compute",
            B:"FWER 在 20,000 基因下幾乎拒絕不了任何假設；FDR 控制錯誤發現比例，保留發現能力", B_en:"FWER kills power for 20,000 genes; FDR controls the fraction of false discoveries, preserving discovery power",
            C:"FDR 與 FWER 在數值上相同", C_en:"FDR equals FWER numerically",
            D:"FWER 不存在", D_en:"FWER does not exist",
            ans:"B",
            exp:"Bonferroni α/m 在 m=20,000 時極為嚴格；FDR 容忍少量假陽性以維持探索性研究的能量。",
            exp_en:"Bonferroni α/m is extreme when m=20,000; FDR tolerates a small fraction of false positives to keep exploratory power." },
          { type:"single",
            stem:"q-value = 0.05 精確的意義是？",
            stem_en:"What does a q-value of 0.05 mean — precisely?",
            A:"5% 的型 I 錯誤率", A_en:"5% Type I error rate",
            B:"以此 q 為門檻所宣告的顯著結果中，預期錯誤發現比例為 5%", B_en:"Among rejections at this q-threshold, the expected proportion of false discoveries is 5%",
            C:"模型可信度 95%", C_en:"95% model credibility",
            D:"Power = 95%", D_en:"Power = 95%",
            ans:"B",
            exp:"q-value 是「pFDR 控制」量度，不是 p-value，不能解讀為單一假設的型 I 錯誤率。",
            exp_en:"q-value measures pFDR control, not a Type I error rate for a single hypothesis." },
          { type:"tf",
            stem:"是非題：Benjamini-Hochberg (BH) 程序在 positive regression dependence (PRDS) 下仍能正確控制 FDR。",
            stem_en:"True/False: The Benjamini-Hochberg (BH) procedure controls FDR even under positive regression dependence (PRDS).",
            ans:"T",
            exp:"Benjamini-Yekutieli (BY) 適用任意相依但較保守；BH 在 PRDS（基因體中常見）下仍有效。",
            exp_en:"Benjamini-Yekutieli (BY) handles arbitrary dependence but is conservative; BH remains valid under PRDS (common in genomics)." }
        ],
        "Step 15：差異表現統計": [
          { type:"single",
            stem:"voom 在套用 limma 之前對 RNA-seq counts 做什麼，為何必要？",
            stem_en:"What does voom do to RNA-seq counts before applying limma, and why is it necessary?",
            A:"取 log2(CPM+0.5)，並對每個 (基因, 樣本) 計算精度權重以對應 mean-variance trend", A_en:"Takes log2(CPM+0.5) and computes precision weights per (gene, sample) to match the mean-variance trend",
            B:"標準化到 0-1", B_en:"Normalizes to 0–1",
            C:"刪除高變異基因", C_en:"Removes highly variable genes",
            D:"做 PCA", D_en:"Performs PCA",
            ans:"A",
            exp:"voom 用精度權重把計數資料「轉成」可放進 limma 高斯線性模型——同時保留 mean-variance 關係。",
            exp_en:"voom uses precision weights to bring count data into limma's Gaussian framework while preserving mean-variance structure." },
          { type:"single",
            stem:"DESeq2 的 lfcShrink() 對 low-count 基因為何特別重要？",
            stem_en:"Why is DESeq2's lfcShrink() especially important for low-count genes?",
            A:"低計數基因的原始 log fold change 變異極大、極不穩定，shrinkage 能給出可信的排序與圖示", A_en:"Raw LFCs of low-count genes are wildly noisy; shrinkage gives reliable ranking and visualization",
            B:"它修改 p-value", B_en:"It modifies the p-value",
            C:"它使 FDR 自動變小", C_en:"It automatically reduces the FDR",
            D:"與 low count 無關", D_en:"It has nothing to do with low counts",
            ans:"A",
            exp:"使用 apeglm/ashr/normal 等先驗對 LFC 收縮，是 ranking 與火山圖呈現的標準作法。",
            exp_en:"Shrinking LFCs with apeglm/ashr/normal priors is standard for ranking and volcano-plot display." },
          { type:"tf",
            stem:"是非題：「先用 ComBat 移除 batch、再做 DE」與「將 batch 放入 design matrix」等價。",
            stem_en:"True/False: 'Remove batch first with ComBat, then run DE' is equivalent to 'include batch in the design matrix'.",
            ans:"F",
            exp:"前者使 SE 失真且不傳播 batch 校正的不確定性；正確作法是直接把 batch 納入 design。",
            exp_en:"The former distorts SEs and ignores uncertainty in the batch correction; the correct approach is including batch in the design." }
        ],
        "Step 16：排列、Bootstrap、GSEA": [
          { type:"single",
            stem:"為什麼樣本排列 (sample permutation) 比基因排列 (gene permutation) 給出更保守、更正確的 GSEA p-value？",
            stem_en:"Why does sample-label permutation give a more conservative and correct GSEA p-value than gene permutation?",
            A:"樣本排列計算更快", A_en:"Sample permutation is faster",
            B:"基因排列假設基因間獨立，忽略 inter-gene correlation 而使型 I 錯誤膨脹", B_en:"Gene permutation assumes inter-gene independence and inflates Type I",
            C:"基因排列違反基因表達基本物理", C_en:"Gene permutation violates physics",
            D:"沒有差別", D_en:"There is no difference",
            ans:"B",
            exp:"基因排列把 gene set 與其餘基因隨機交換，但實際基因間高度相關，導致虛無分布太窄。",
            exp_en:"Gene permutation randomly swaps the gene set with the rest, ignoring strong inter-gene correlation — producing too-narrow null." },
          { type:"single",
            stem:"何時 bootstrap 比 permutation 更適合？",
            stem_en:"When is the bootstrap preferable to a permutation test?",
            A:"想評估參數估計的標準誤與信賴區間（permutation 只給 p-value）", A_en:"Estimating standard errors and CIs for a parameter (permutation only yields a p-value)",
            B:"想直接得 p-value", B_en:"Directly computing a p-value",
            C:"資料極度相關", C_en:"Strongly correlated data",
            D:"資料極小 (n<5)", D_en:"Very small n (<5)",
            ans:"A",
            exp:"Permutation 是檢定 (對虛無)，bootstrap 是估計 SE/CI 的方法。",
            exp_en:"Permutation is for hypothesis testing; bootstrap is for SE/CI estimation." },
          { type:"tf",
            stem:"是非題：CAMERA/ROAST 等「competitive」gene-set test 會考慮 gene-set 內基因間的相關性，而 hypergeometric (ORA) 不會。",
            stem_en:"True/False: Competitive tests like CAMERA/ROAST account for inter-gene correlation within a set, while hypergeometric (ORA) does not.",
            ans:"T",
            exp:"ORA 假設基因獨立——在 RNA-seq 中常違反；CAMERA 利用估計的 inter-gene correlation 修正。",
            exp_en:"ORA assumes independent genes — frequently violated in RNA-seq; CAMERA adjusts via estimated inter-gene correlation." }
        ],
        "Step 17：存活分析": [
          { type:"single",
            stem:"何為「非資訊性截尾 (non-informative censoring)」假設，違反時會怎樣？",
            stem_en:"State the non-informative censoring assumption and what happens when it is violated.",
            A:"截尾與事件機率無關；違反時 KM 與 Cox 偏誤", A_en:"Censoring is independent of event probability; KM/Cox become biased if violated",
            B:"所有事件必須觀察到", B_en:"All events must be observed",
            C:"截尾要在固定時間", C_en:"Censoring must occur at fixed times",
            D:"與假設無關", D_en:"No assumption involved",
            ans:"A",
            exp:"若「病情惡化導致退出」則截尾資訊性強——KM 高估存活，Cox 偏誤需用敏感度分析或 joint model。",
            exp_en:"If sicker patients drop out, censoring is informative — KM overestimates survival; sensitivity analysis or joint models are needed." },
          { type:"single",
            stem:"Schoenfeld residuals 用於診斷什麼？",
            stem_en:"What do Schoenfeld residuals diagnose?",
            A:"非線性", A_en:"Non-linearity",
            B:"比例風險 (proportional hazards) 假設是否成立——殘差對時間呈非零斜率即代表違反", B_en:"Whether the proportional hazards assumption holds — a non-zero slope vs time signals violation",
            C:"異質變異", C_en:"Heteroscedasticity",
            D:"競爭風險", D_en:"Competing risks",
            ans:"B",
            exp:"cox.zph() 對 Schoenfeld 殘差檢定；違反時改用 time-varying coefficient、stratification 或 RMST。",
            exp_en:"cox.zph() tests Schoenfeld residuals; if violated use time-varying coefficients, stratification, or RMST." },
          { type:"tf",
            stem:"是非題：把連續生物標誌物 (biomarker) 在中位數切兩半再丟進 Cox，比直接用連續變數更合理。",
            stem_en:"True/False: Dichotomizing a continuous biomarker at the median before Cox is statistically better than using it continuously.",
            ans:"F",
            exp:"切割丟失資訊、損失檢定力；若以「最佳切點」搜尋還會嚴重膨脹型 I 錯誤；改以連續變數或 spline 較佳。",
            exp_en:"Dichotomization discards information and reduces power; an 'optimal cutpoint' search inflates Type I; use continuous or spline terms instead." }
        ]
      }
    }
  }
};
